In [111]:
import numpy as np

In [161]:
a = [1,2,3,4]
b = [5,6,7,8]

In [113]:
output = []
for i,j in zip(a,b):
    output.append(i+j)

In [114]:
print(output)

[6, 8, 10, 12]


In [115]:
g = list(range(1000000))

In [116]:
%timeit sum(g)

24.4 ms ± 589 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [119]:
h = np.array(g)

int

In [120]:
type(h)

numpy.ndarray

In [121]:
%timeit np.sum(h)

415 µs ± 7.57 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [164]:
#all ops in numpy unless speicfied are point to point

a=np.array(a)
b=np.array(b)
print(type(a))
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [142]:
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [136]:
a+b

array([ 6,  8, 10, 12])

In [137]:
a-b

array([-4, -4, -4, -4])

In [138]:
a*b

array([ 5, 12, 21, 32])

In [139]:
a**b

array([    1,    64,  2187, 65536], dtype=int32)

In [ ]:
a**2

In [143]:
a+20

array([21, 22, 23, 24])

In [144]:
a.dtype  #int64 in mac/linux

dtype('int32')

In [145]:
m = np.sin(a)
n = np.log(a)
o = np.exp(a)
print(m)
print(n)
print(o)

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.         0.69314718 1.09861229 1.38629436]
[ 2.71828183  7.3890561  20.08553692 54.59815003]


In [146]:
a.ndim

1

In [147]:
a.shape #note that this is a tuple because of the comma

(4,)

## Note : A tuple is a tuple because of the comma, NOT the brackets

In [148]:
x = (10)
type(x)

int

In [149]:
x = 10,
type(x)

tuple

In [ ]:
#the base code is written in C, for speed, you can check by checking type

In [150]:
np.log

<ufunc 'log'>

In [ ]:
np.sum #numpy at it's base will end up with c code

In [157]:
a = [1,2,3]
b = (1,2,3)
b[0]=5

TypeError: 'tuple' object does not support item assignment

In [162]:
#numpy arrays are mutable
print(a)

a[0] = -1

print(a)

[1, 2, 3, 4]
[-1, 2, 3, 4]


In [165]:
print(a)
a.dtype

[-1  2  3  4]


dtype('int32')

In [166]:
#adding float to this array leads to truncating of the decimal
a[3] = 10.12
a

array([-1,  2,  3, 10])

In [167]:
a.fill(4)
a

array([4, 4, 4, 4])

In [168]:
a.fill(4.8)
a

array([4, 4, 4, 4])

In [170]:
#when initialzing if all elements if anyone is float or complex, the entire array becomes that
a = np.array([1,2,3,4])
print(a.dtype)

a = np.array([1,2,3,4.21])
print(a.dtype)
print(a)

int32
float64
[1.   2.   3.   4.21]


In [171]:
#you can also declare dtype as an argument in the array constructors
a = np.array([1,2,3,4.31],dtype='int32')
print(a)

[1 2 3 4]


In [172]:
a = np.array([1,2,3,4],dtype='float64')
print(a)

[1. 2. 3. 4.]


## Higher Dimensions : list of lists

In [173]:
x = [10,11,12]
y = [20,21,22]

a = np.array([x,y])
a

array([[10, 11, 12],
       [20, 21, 22]])

In [174]:
a.dtype

dtype('int32')

In [175]:
a.ndim

2

In [176]:
a.shape

(2, 3)

In [179]:
print(a)
a.T #transpose

[[10 11 12]
 [20 21 22]]


array([[10, 20],
       [11, 21],
       [12, 22]])

In [178]:
x=np.array(x)
x.T

array([10, 11, 12])

In [180]:
x.shape

(3,)

In [ ]:
a.nbytes

In [181]:
a

array([[10, 11, 12],
       [20, 21, 22]])

In [182]:
 a[0]

array([10, 11, 12])

In [183]:
a[0,0] #don't do chained brackets like a[0][0]

10

In [184]:
a=np.array([10,11,12,13,14])
a

array([10, 11, 12, 13, 14])

In [185]:
a[1:3]

array([11, 12])

In [186]:
a[1:-2]

array([11, 12])

In [187]:
a[-4:3] #don't do this

array([11, 12])

In [200]:
a[:3] #first three elements

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25]])

In [188]:
# a[-2:]
a

array([10, 11, 12, 13, 14])

In [189]:
a[::2]

array([10, 12, 14])

In [202]:
a = [[0,1,2,3,4,5],[10,11,12,13,14,15],[20,21,22,23,24,25],[30,31,32,333,34,35],[40,41,42,43,44,45],[50,51,52,53,54,55]]
a=np.array(a)
print(a)
print(a[4::,4::])

[[  0   1   2   3   4   5]
 [ 10  11  12  13  14  15]
 [ 20  21  22  23  24  25]
 [ 30  31  32 333  34  35]
 [ 40  41  42  43  44  45]
 [ 50  51  52  53  54  55]]
[[44 45]
 [54 55]]


In [191]:
a[0]

array([0, 1, 2, 3, 4, 5])

In [192]:
a[0,3:5]

array([3, 4])

In [193]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [194]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [195]:
a[2:6:2,:6:2]

#a[2::2,::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [203]:
x = [1,2,3] 

In [204]:
print(x[0]) #indexing loses the dimension
print(x[:1]) #slicing doesn't

1
[1]


In [205]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
a[4,:]

In [ ]:
a[:,1:4:2]
#a[:,1::2]

In [ ]:
a[1:4:2,:4:2]
#a[1::2,:4:2]

In [ ]:
sub = a[1:4:2,:4:2]
sub

In [ ]:
sub.flags

In [ ]:
a.flags

In [ ]:
sub[1,1] = 2
print(sub) #changing sub changes a
print(a)

In [206]:
a = np.arange(0,80,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70])

In [207]:
#fancy indexing
indices = [0,1,5]
a[indices]

array([ 0, 10, 50])

In [208]:
#manual creation of masks
mask = np.array([1,1,0,0,0,1,0,0],dtype=bool)
a[mask]

array([ 0, 10, 50])

In [209]:
a = np.array([0,-1,2,3,-4,5,6])
a

array([ 0, -1,  2,  3, -4,  5,  6])

In [210]:
a < 0

array([False,  True, False, False,  True, False, False])

In [211]:
a[a<0]
#pass the mask as fancy indexing

array([-1, -4])

In [ ]:
a

In [ ]:
a[a<0]=0
a

In [212]:
b = np.zeros((2,2))
b

array([[0., 0.],
       [0., 0.]])

In [213]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0, 0])

In [214]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [215]:
np.full((3,2),5)

array([[5, 5],
       [5, 5],
       [5, 5]])

## Broadcasting

In [216]:
a = np.array([1,2,3,4,5])
b = 3
c = a+b
c

array([4, 5, 6, 7, 8])

In [217]:
a = np.arange(25).reshape(5,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [218]:
b = np.arange(5).reshape(5,1)
b

array([[0],
       [1],
       [2],
       [3],
       [4]])

In [219]:
a + b 

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10],
       [12, 13, 14, 15, 16],
       [18, 19, 20, 21, 22],
       [24, 25, 26, 27, 28]])

In [220]:
b + 5

array([[5],
       [6],
       [7],
       [8],
       [9]])

In [221]:
a + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

  **Function Name -	NaN-safe Version -	Description**

1. np.sum 	  -      np.nansum   -	Compute sum of elements

2. np.prod    - 	np.nanprod   -	Compute product of elements

3. np.mean    -  	np.nanmean   -	Compute mean of elements

4. np.std     -  	np.nanstd    -	Compute standard deviation

5. np.var     - 	np.nanvar    -	Compute variance

6. np.min     -  	np.nanmin    -	Find minimum value

7. np.max     -  	np.nanmax    -	Find maximum value

8. np.argmin  -  	np.nanargmin -	Find index of minimum value

9. np.argmax  -  	np.nanargmax -	Find index of maximum value

10. np.median -  	np.nanmedian -	Compute median of elements

11. np.percentile -	np.nanpercentile - Compute rank-based statistics of elements

12. np.any    -  	N/A 	     -     Evaluate whether any elements are true

13. np.all 	  -     N/A 	     -     Evaluate whether all elements are true